import { expect, test } from '@playwright/test'
import { activeChatId, countRows, freshPage, manualStreams, send } from './helpers'

/** Mid-reply behaviour, driven chunk by chunk through manualStreams(). */
test.describe('streaming', () => {
  test('stop keeps the partial reply, and it survives a reload', async ({ page }) => {
    const streams = await manualStreams(page)
    await freshPage(page)
    await send(page, 'Tell me a story')
    await expect.poll(streams.count).toBe(1)
    await streams.push(0, 'Once upon a time')
    await expect(page.getByTestId('ai-message')).toContainText('Once upon a time')
    await page.getByTestId('stop-btn').click()
    await expect(page.getByTestId('ai-message')).toHaveAttribute('data-status', 'aborted')
    await expect(page.getByTestId('ai-message')).toContainText('Stopped')
    // The status flips just before the final save resolves; let the write land before reloading
    await page.waitForTimeout(300)
    await page.reload()
    await expect(page.getByTestId('ai-message')).toContainText('Once upon a time')
    await expect(page.getByTestId('ai-message')).toHaveAttribute('data-status', 'aborted')
  })

  test('a reply cut off by a reload is repaired and can be regenerated', async ({ page }) => {
    const streams = await manualStreams(page)
    await freshPage(page)
    await send(page, 'Long answer please')
    await expect.poll(streams.count).toBe(1)
    await streams.push(0, 'Part one. ')
    // Let the throttled save write the partial text
    await page.waitForTimeout(700)
    await streams.push(0, 'Part two.')
    await page.reload()
    const reply = page.getByTestId('ai-message')
    await expect(reply).toHaveAttribute('data-status', 'aborted')
    await expect(reply).toContainText('Part one.')
    await expect(page.getByTestId('regenerate-btn')).toBeVisible()
  })

  test('Esc stops the reply even when focus is outside the message box', async ({ page }) => {
    const streams = await manualStreams(page)
    await freshPage(page)
    await send(page, 'Go')
    await expect.poll(streams.count).toBe(1)
    await streams.push(0, 'Working')
    await page.getByTestId('chat-title').focus()
    await page.locator('body').press('Escape')
    await expect(page.getByTestId('ai-message')).toHaveAttribute('data-status', 'aborted')
  })

  test('a background reply keeps writing to its own chat after switching', async ({ page }) => {
    const streams = await manualStreams(page)
    await freshPage(page)
    await send(page, 'Chat A question')
    await expect.poll(streams.count).toBe(1)
    await streams.push(0, 'Answer for A, ')
    const chatA = await activeChatId(page)

    await page.getByTestId('new-chat-btn').click()
    await send(page, 'Chat B question')
    await expect.poll(streams.count).toBe(2)
    await streams.push(1, 'Answer for B')
    await streams.done(1)
    await expect(page.getByTestId('ai-message')).toHaveAttribute('data-status', 'done')

    await streams.push(0, 'continued.')
    await streams.done(0)
    await expect(page.getByTestId('ai-message')).toHaveText(/^Answer for B/)

    // Both chats get auto-titled by the mock; the list is newest-first, so A is second
    await page.getByTestId('chat-item').nth(1).getByRole('button').first().click()
    expect(await activeChatId(page)).toBe(chatA)
    await expect(page.getByTestId('ai-message')).toContainText('Answer for A, continued.')
    await expect(page.getByTestId('ai-message')).toHaveAttribute('data-status', 'done')
  })

  test('deleting a chat mid-reply stops it and leaves no rows behind', async ({ page }) => {
    const streams = await manualStreams(page)
    await freshPage(page)
    await send(page, 'Doomed')
    await expect.poll(streams.count).toBe(1)
    await streams.push(0, 'Some text')
    const chatId = await activeChatId(page)
    await page.getByTestId('chat-item').hover()
    await page.getByRole('button', { name: /Actions for/ }).click()
    await page.getByTestId('delete-chat-btn').click()
    await page.getByTestId('confirm-btn').click()
    await expect(page.getByTestId('chat-item')).toHaveCount(0)
    await page.waitForTimeout(700)
    expect(await countRows(page, 'nodes', chatId)).toBe(0)
    expect(await countRows(page, 'conversations')).toBe(0)
  })

  test('regenerate cannot start a second reply while one is running', async ({ page }) => {
    const streams = await manualStreams(page)
    await freshPage(page)
    await send(page, 'Q')
    await expect.poll(streams.count).toBe(1)
    await streams.push(0, 'First')
    await streams.done(0)
    await expect(page.getByTestId('ai-message')).toHaveAttribute('data-status', 'done')
    await page.getByTestId('regenerate-btn').click()
    await expect.poll(streams.count).toBe(2)
    await expect(page.getByTestId('regenerate-btn')).toHaveCount(0)
    await expect(page.getByTestId('stop-btn')).toBeVisible()
    await page.getByTestId('chat-textarea').fill('another')
    await page.getByTestId('chat-textarea').press('Enter')
    await page.waitForTimeout(200)
    expect(await streams.count()).toBe(2)
  })

  test('a dropped connection shows an error with Retry', async ({ page }) => {
    const streams = await manualStreams(page)
    await freshPage(page)
    await send(page, 'Q')
    await expect.poll(streams.count).toBe(1)
    await streams.push(0, 'Half an ans')
    await streams.drop(0)
    await expect(page.getByTestId('message-error')).toContainText('ended unexpectedly')
    await page.getByTestId('message-error').getByRole('button', { name: 'Retry' }).click()
    await expect.poll(streams.count).toBe(2)
    await streams.push(1, 'Full answer')
    await streams.done(1)
    await expect(page.getByTestId('ai-message')).toContainText('Full answer')
  })

  test('chat settings keep a Think toggle made while the panel is open', async ({ page }) => {
    await freshPage(page)
    await page.getByTestId('model-select').click()
    await page.getByTestId('model-option-qwen3').click()
    await send(page, 'Hi')
    await expect(page.getByTestId('ai-message')).toHaveAttribute('data-status', 'done')
    await page.getByTestId('chat-settings-btn').click()
    await page.getByTestId('think-toggle').click()
    await expect(page.getByTestId('think-toggle')).toContainText('off')
    await page.getByTestId('system-prompt-input').fill('Be terse')
    await page.getByTestId('save-chat-settings').click()
    await expect(page.getByTestId('think-toggle')).toContainText('off')
  })
})
